### ISSUE TITLE
Request to Include Paper: DGA-GNN

### ISSUE THREAD

**Issue by AtwoodDuan** [safe-graph/graph-fraud-detection-papers#25]
Hello ,

I hope this message finds you well. I am writing to request the inclusion of our recent paper in your esteemed paper list repository. 

Below are the details of the paper:

**Title:** DGA-GNN: Dynamic Grouping Aggregation GNN for Fraud Detection
**Paper:** https://ojs.aaai.org/index.php/AAAI/article/view/29067
**Code:** https://github.com/AtwoodDuan/DGA-GNN
**Authors:** Mingjiang Duan, Tongya Zheng, Yang Gao, Gang Wang, Zunlei Feng, Xinyu Wang
**Published at**: AAAI 2024
**Key Contributions:** Our paper introduces DGA-GNN, a novel approach that leverages dynamic grouping aggregation in Graph Neural Networks for enhanced fraud detection. This methodology not only achieves advanced effectiveness on fraud detection dataset but also addresses a novel scientific challenge related to the non-additivity of features. These contributions underscore the paper's potential impact and relevance to the community.

We believe that our paper aligns well with the themes of your repository and would be a valuable addition, offering unique insights and methodologies that could benefit researchers and practitioners in the field.

**Comment by YingtongDou** [comment]
Thanks for the update. Please make a PR if you would like to contribute :)

**Comment by AtwoodDuan** [comment]
Thank you very much for your reminder; I have already submitted a PR  :)
