### ISSUE TITLE
Fix some paper links and code?

### ISSUE THREAD

**Issue by rickyxume** [safe-graph/graph-fraud-detection-papers#6]
KDD'21 Workshop: _Relational Graph Neural Networks for Fraud Detection in a Super-App environment_ [[link](https://arxiv.org/pdf/2107.13673.pdf)]
SIGIR'20: _GCN-Based User Representation Learning for Unifying Robust Recommendation and Fraudster Detection_ [[code](https://github.com/zsjdddhr/GraphRfi)]

**Comment by YingtongDou** [comment]
Fixed, thanks!
